default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: verve_arena_e_commerce_backend_development

test:
  <<: *default
  database: verve_arena_e_commerce_backend_test

production:
  <<: *default
  database: verve_arena_e_commerce_backend_production
  username: verve_arena_e_commerce_backend
  password: <%= ENV["VERVE_ARENA_E_COMMERCE_BACKEND_DATABASE_PASSWORD"] %>
